on:
  push:
    branches: [ "main" ]

jobs:
  job2:
    runs-on: ubuntu-latest
    name: Deploy to gh-pages
    needs: job1
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.100-preview.4.23260.5
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish
      run: dotnet publish -c Release -o release
    - name: Push to gh-pages branch
      env:
        SRC_FOLDER_PATH: 'release\wwwroot'
        TARGET_BRANCH: 'gh-pages'
      run: |
        files=$(find $SRC_FOLDER_PATH -type f) # get the file list
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git fetch                         # fetch branches
        git checkout $TARGET_BRANCH       # checkout to your branch
        git checkout ${GITHUB_REF##*/} -- $files # copy files from the source branch
        git add -A
        git diff-index --quiet HEAD ||  git commit -am "deploy files"  # commit to the repository (ignore if no modification)
        git push origin $TARGET_BRANCH # push to remote branch
